= jan Kali
:nofooter:
:linkcss:
:stylesheet: ./style.css

:compress:
:pdf-theme: ./resume.yml

ifdef::backend-pdf[]
[.center,cols="3*^",width="75%",frame="none",grid="none"]
|===
|mailto:kylie@somas.is[]|https://somas.is/|https://www.openstreetmap.org/relation/178973[ma tomo Pune, lon ma lili Nokawolana]
|===
endif::[]

xref:resume.adoc[Available in English as well!]

ifndef::backend-pdf[]
link:resume.pdf[lipu ni li lon nasin lipu PDF kin.]
endif::[]

[.text-center]
toki!
mi jan Kali. tenpo sike 23 la mi lon.

mi jan pi kama sona. mi kama sona e nasin sona (nimi "philosophy" lon toki Inli). +
mi tan ma Nokawolana (nimi "North Carolina" lon toki Inli).

sina wile kama sona mute e pali mi la, o pana e toki tawa ilo Email mi. +
ilo Email la mi nimi mailto:kylie@somas.is[].
mi ken pana e sona mute.

:url-debian: https://debian.org
:url-arch: https://archlinux.org
:url-alpine: https://alpinelinux.org
:url-exherbo: https://exherbo.org
:url-musllibc: https://musl.libc.org
:url-skarnet: https://www.skarnet.org
:url-execline: {url-skarnet}/software/execline
:url-s6: {url-skarnet}/software/s6

== pali

:url-tss: https://support.appstate.edu/services/technology-support-center

* *jan pona pi ilo sona* lon {url-tss}[pona pali pi ilo sona lon tomo sona suli Apalasin]
  _(tenpo sike 2018-lon)_
    ** mi weka e jaki tan ilo sona. mi awen e lipu lon ilo sona. mi lukin e kon pakala pi ilo sona.
       mi lawa e lipu pi wile pona kepeken ilo Jira.
    ** mi toki tawa jan wile.
       jan wile li kama lon tomo pali mi la, ona li wile e ilo sona ona la,
       mi pana e toki pi nasin pona tawa ona.
    ** lon jan pi pali mi la, ona sona e ni:
       nasin Linu lon ilo sona la, mi jan pali nanpa wan. `:-)`

== sona

* https://appstate.edu[jan pi kama sona lon tomo sona suli Apalasin] _(tenpo sike 2018-lon)_
    ** mi wile e *sona nanpa wan pi nasin sona*.
       sona nasin pi kule kon, en sona pi nasin meli mi, en sona pi nasin unpa la,
       mi wile e *sona nanpa tu ni.*
    ** tenpo pi sona ni pini la mi kama sona e sona suli pi nasin sona nanpa pini.

=== pali lon poka ni

:url-linuxatapp: https://engage.appstate.edu/organization/linux-app

* *jan pali* lon kulupu pona pi nasin sona lon tomo sona suli Apalasin _(tenpo sike 2021-lon)_
* *jan pali nanpa tu* lon kulupu pona pi nasin sona lon tomo sona suli Apalasin _(tenpo sike 2021)_
* jan lon kulupu pona pi nasin sona lon tomo sona suli Apalasin _(tenpo sike 2019-lon)_
* jan lon ({url-linuxatapp}[kulupu pona pi nasin Linu lon tomo sona suli Apalasin]
  _(tenpo sike 2018-tenpo sike 2019)_

== sona pali en wile mi

*ilo lon ilo sona*::
    {url-alpine}[*nasin Alpin Linu*], {url-exherbo}[_nasin Ekihepo Linu_],
    {url-arch}[*nasin Awe Linu*], {url-debian}[nasin Tepin GNU/Linu], nasin Winto,
    *ilo POSI Selo/Pasi*, {url-musllibc}[*_ilo Musa Lipese_*], {url-s6}[*_ilo s6_*],
    {url-execline}[*_ilo Ekeline_*].
    o toki e nimi ilo lon nasin Juni la, ken la mi kepeken ilo ni.

*sona pi kepeken ilo*::
    *ilo Jira*, *lipu GitHub*, lipu GitLab, ilo Gerrit, *ilo Gitolite*

*wile*::
    wile nasin lili, lawa nasin, lili nasin.

[small]#_sitelen pi lukin Italija_: tenpo pini la mi pana e pali tawa kulupu ni.
*sitelen wawa*: mi kepeken ni.#

== pali pi mani ala

* *jan pali suli*, lon kulupu pali pi {url-exherbo}[nasin Ekihepo Linu]
  _(tenpo sike 2014-tenpo sike 2017)_
    ** lon ilo toki IRC la, mi pali lon poka jan pali ante 20.
    ** mi pana e ken pi nasin sin. nasin sin mute li {url-musllibc}[ilo Musa Lipese], li nasin ilo ARMv7.
    ** mi sitelen e lipu pali pi open nasin.
    ** mi sitelen e lipu pali pi kon tan jan pali ante.

== pali lili mi

* https://mutiny.red[nasin Mutini], li poki pi nasin Linu, li kulupu pi kama sona.
  nasin ni li wile nasin ni pi ilo sona: wile wan, en wile pona, en wile musi.
  _(tenpo sike 2016-pali lape)_
* https://wiki.musl-libc.org[lipu kulupu pi ilo Musa Lipese], li pali e lipu sona pi ilo ni kepeken
  kulupu pi jan kepeken. mi awen e ilo pali pi lipu ni, e lipu kule.
  _(tenpo sike 2016-lon; pali mi li lili lon tenpo lon pi sike 2020.)_

== musi mi

* https://somasis.bandcamp.com[kalama musi], kepeken ilo FL Studio.
  _(tenpo sike 2012-lon, ken la ni li awen lon tenpo pi ale pini mi)_
* mi pana e sona lili tawa lipu https://openstreetmap.org/user/somasis[OpenStreetMap]. +
  ni li pana e ni tawa mi: mi sona e ma ale lon poka mi, e pona pi kulupu mi. +
  ma pi mi lon la mi pana e sona pi ma ni tawa lipu ma ni.
* mi kama sona, mi toki uta, mi sitelen, kepeken https://en.wikipedia.org/wiki/Toki_Pona[toki pona].
  toki pona li toki tomo; jan li sona e toki ni tan lili ona. _o toki pona tawa mi._
