= nature as body / body as nature
:description: 
:docdate: 2021-12-07
:keywords: nature, body, philosophy, critical theory

We do not change the world by feeling bad for our participation in it; we change it by changing
the ways that things are done.

Nature takes importance as the stage of which the actors of world-historical forces lay their
claims on transforming. When I speak of world-historical moments, they are these: the Renaissance,
the Enlightenment, the colonizing of the New World, the Industrial Revolution. All these events had
the same ideological basis: nature was hiding something from us. We will come to know it, and we
will transform our relation to nature, and then transform the nature which we have available to
relate to.

The Renaissance's goal more specifically, to know the power of men without subjectivity,
ideological speaking, laid the foundations for which the Enlightenment could hope to know nature
without subjectivity. Furthermore, it would come to, once known, dominate that nature and realize
the full potential of man to change it. This change is the ideologically-bound desire which would
come alienate us from a specific form of nature, in the Industrial Revolution.

When the Revolution came, we experienced massive centralization of economic power unlike anything
the land had seen before; and the land had seen quite a lot, by this point: The expunging of
Indigenous tribal land continued, the expanse westward would follow, an expanse which could only be
taught as genocides and a moment by which genocidal angels appearing as their original Biblical
sense came down, but our artists could only paint them as white women. Instead, the ideological
view is that this is a time of expansion, a reclamation of the nature, if not a continuation of
that Enlightenment, but in a more physical sense. If the Age of Reason was seeking to fully explain
our _a priori_, then the expansion would seek out to realize our purpose for landing on the rock
all those years ago: reaching the other side of it.

When nature came, it did not first come for the colonizers. They may have died to it at times, but
at no time did they die to something truly ancient, as though it may feel. The nature by which
colonizers died was the heat, the sun, the lack of East Coast green. What nature the Indigenous
peoples are still dying from now is something more ancient, something that would come to be known
by many in due time: alienation from it. Being alienated in the physical sense from the land which
they were one with from time immemorial was one thing, but their villages burned and people
violated, they too suffered what could only lightly be called an alienation from their labor. Taken
away from a land with which one toils on for eternity, with which a person does not only toil _on_,
but toils _with_, and _as_, is a grave alienation, an alienation from memory and place.

In "The Critique of the Philosophy of History", from the _Dialectic of Enlightenment_, Horkheimer &
Adorno discuss the interpretation of history that brings this on. "Liberation of citizens from the
injustice of the feudalistic or absolutist past served to unleash modern machinery through
liberalism [...] The spirit and all that is good in its origins and existence are inextricably
caught up in this network of horror." (223; par. 1) No matter what good is had now in our world,
there is a violence at the basis of it which we've not yet fully discovered and reckoned with,
which lies in Nature.

Nature as it stands has been thoroughly made feminine, as women bear children nature too has born
man. (Davis 148; par. 4) As coming of age brings leaving of home, a leaving of place and formation
of new memory, so to the motherhood of nature has forever ended in our historical notions of what
exactly nature is, and what it did to us. We are now adults who are differentiated and independent,
and who wish to express that we were always different from that mother in a way she could never
truly grasp. The same mother which gave us life can take it away, for so long as she supports us,
she could at any time swallow us up in flame. But she misses us, and wishes we would visit and call
more often.

For as much as we claim otherwise, nature is not a thing separate from us, nor are we separate from
it. Nature resists being split apart like this, which shows through the way we split apart our own
lives when we split apart nature. Angela Davis discusses the natural state of humans (through a
reading of Marx) and gets at this: Humans are natural beings, because when we act with our
biological powers and drives, we can only survive by acting upon and transforming nature (Davis
150; par. 3). Quoting Marx, she says “labor is a natural condition of human existence, a
condition of material interchange between men and nature quite independent of the form of
society”; when we modify and do things to nature, or use nature for our own gains, we create and
transform our own nature. Labor is always social, as it is reliant on the works of others and the
labor of others, through the chain of products, sourcing of materials, and reproductive labor that
makes further labor possible to even be engaged in in the first place. Therefore, the manipulation
of our social structure and the way we organize labor also affects the way we engage with nature,
and the manipulation of nature must affect the way we engage in our social structure. The removal
of nature from ourselves and the unwillingness to put into conversation our nature and our
construction, ends up obscuring and obliterating the two in the process, despite never truly
destroying one or the other. It is instead reified as a discussion to be had in pure sociological
terms—are we nature, or nurture, or something in between? The possibility of both constantly
becoming the other, constantly taking apart one and becoming it in the process, is null.

Often when we talk about human nature we are selling a proposition. The ideological school will say
that human nature is still yet undetermined, but despite that we can assume it takes on the color
of a selfishness and individualism, with each human an island, their individual rational decisions
making society as a way to avoid nature’s violence, a cleavage separating firmament from waters.

Avoiding the New Age misdirection, a closeness to Nature _is_ in fact a distance from alienation;
it is not the way to happiness, but it is a way from this specifically cutting form of sadness and
depression. This is because when we change the methods of our labors, and thus we change our human
nature, we also change our imagination of things as vast as oppression and liberation, nature and
construction, profit and surplus, and the true transcending of those. The metamorphosis of
oppression is its undoing as liberation, but it is also its continued doing as an unconfronted
essence, merely pushed further down the scale from an immediate to a passive concept. One needs
something custom, fashioned as an artesian work, to respond to the changing relations; because
though this appears dynamic, it is merely through never addressing the hidden immobility of
labor’s relationship to nature that we arrive at this appearance.

In “Imperial Panorama” (40; par. 2), from Benjamin’s _One-Way Street_, a caution is given:

____
_The earliest customs of peoples seem to send us a warning that, in
accepting what we receive so abundantly from nature, we should guard against a gesture of avarice.
For we are unable to make Mother Earth any gift of our own. It is therefore fitting to show respect
in taking, by returning a part of all we receive before laying hands on our share. […] If society
has so denatured itself through necessity and greed that it can now receive the gifts of nature
only rapaciously–that it snatches the fruit unripe from the trees in order to sell it most
profitably, and is compelled to empty each dish in its determination to have enough – the earth
will be impoverished and the land will yield bad harvests._
____

As we could easily take this caution and as a polemic against industrious activity, we must
recognize that this is a dialectical moment. Our industry has given us medication, health care
breakthroughs, has fed and clothed many, and if distributed correctly it could end much material
suffering. But it has never truly transcended the supposed nature, nor has it ever seeked to change
the basic violence at the root of our organizational structure. No amount of ignoring flames could
amount to such an ascension. Misidentifying social problems and mistargeting them with
technological solutions in what is a fundamentally unstable organization of labor is the issue;
without attempting to actually change and radically reconsider what our organization is and what it
amounts to, all industry and response could be only ever be response, rather than the beginning of
a new discussion entirely. The lucid dialectician asks not for the complete cessation of
industrious activity, but rather for the end of surplus activity, unnecessary activity, harmful
activity. Activity that, so long as it continues, serves to undermine the preservation of the world
we were given in favor of a flawed hierarchy.

As we recognize this relationship, it can come to transform things just as dramatically as any
average revolution of the mind could. Coming out on a good end of the fascist tipping point
however, needs to be the main goal of any revolutionary party; “Hope for better
circumstances—if it is not a mere illusion—is not so much based on the assurance that these
circumstances would be guaranteed, durable, and final, but on the lack of respect for all that is
so firmly rooted in the general suffering.” (“On the Critique” 225). This “lack of
respect” is a disdain for rightly pointing out the need to reorganize and rethink our
relationship to nature. When a party becomes concerned with ideological unity and operational
uniformity rather than u__nity of focus__, the tipping point is upon it.

When it comes to unity of focus, the people who benefit from this structure have always known this.

Labor remains unorganized in this country of genocides, in large because the ideological school has
convinced many that our work and our labor are one in the same. This conflation can explain a lot.

Articulating labor as a crucial part of the human experience, if not perhaps that which makes us
human, can appear utterly crushing and as a relic of oppression itself, if it is not taken with the
important distinction and non-conflation of work and labor. Labor is the doing of things, the
manipulation of the world around you; work is a way that labor gets organized and prescribed. If
one’s entire conception of labor is this current division and never includes experiences like
cooking a meal for people you love, the difficult simple labor of reproductive work, nor the labor
pains of birth, nor composing of an artwork, then labor appears an entirely thankless activity,
inhumane when human. What this conception means is that, so long as the body remains a thing with
which we are bound to rather than included in our thought as part of _I_, the alienation from our
labor remains an infliction of grave consequence; what the case should really be is this: if labor
is what made us human, then it would allow for an entirely new conception of humanity, of
organization and pooling of labor whose only work is seeking out the good of creation. Labor,
rather than a crucible, would be a flourishing.

Nature remains no matter how our organization appears; the only thing that changes is how we relate
to it, and if we view it as untapped resources, or gifts. This nature is not only green, lush
forest, orange desert, or white mountain, it too is the color of flesh, the softness and the
roughness of skin. While “the body is scorned and rejected as something inferior, and at the same
time desired as something forbidden, objectified, and alienated” (232), so too does nature: no
matter how much and for how long we tame it, nature remains the dark forest or the difficult to
scale mountain peak. While “culture defines the body as a thing which can be possessed”, the
body remains a tool rather than part of _I_, which is a relationship is rarely ever a one of
lasting successful identification.

Nature too as tool is an unsuccessful identification; having removed and alienated from land the
Indigenous tribes whose ethical systems saw nature in and of themselves, and vice-versa. A culture
in which “a distinction is made between the body and the spirit” (233), can only ever serve to
allow the visiting of nature, the temporary passing through of the National Park and the Nature
Preserve. “In man’s denigration of his own body, nature takes its revenge for the fact that man
has reduced nature to an object for domination, a raw material.” (233).

As capitalism’s pace quickens and another generation grows older and more adept at fitting into
the confines of this system at its redline, bodies are undergoing this same obscuring and of
memory; a common response to traumatic events. If the domination is finally overcame rather than
sinking into this passing-through-ness, then by regaining and viewing the reduction that took
place, we will also finally become one in unity with our bodies, and with our nature.

=== Works Cited

Benjamin, Walter. “Imperial Panorama.” _One-Way Street_, edited by Michael W. Jennings, translated by Edmund Jephcott, Belknap Press, Cambridge, Massachusetts, USA, 2016, pp. 40–40.

Davis, Angela Y. “Woman and Capitalism: Dialects of Oppression and Liberation.” _The Black Feminist Reader_, edited by Joy James and T. Denean Sharpley-Whiting, Blackwell, Malden, Massachusetts, USA, 2006, pp. 148–152.

Horkheimer, Max, and Theodor Adorno. “On the Critique of the Philosophy of History.” _Dialectic of Enlightenment_, translated by John Cumming, Verso, London, UK, 2016, pp. 222–225.

Horkheimer, Max, and Theodor Adorno. “The Importance of the Body.” _Dialectic of Enlightenment_, translated by John Cumming, Verso, London, UK, 2016, pp. 231–236.
