= computers becoming suburbs
:description: yep
:docdate: 2021-11-10
:keywords: technology, philosophy

Dynamism is a concept that governs an always increasing part of our lives. This might be an easy
observation, and to much of today's working class, indeed it is. With the rise of the "gig economy"
and its accomplice, the present-day tech industry, dynamism is once again the promise that employers
are making to their customers, and that workers are made to adapt to. It is a natural move, it makes
perfect sense; where capitalism has continued to demand more and more efficiency, more and more
increase in speed of production, it also crushes the worker in the gears of the cruel machinery.
Poverty wages in ever-hurried working conditions make for the most dynamic labor pool, the most
effective management of people undergoing ever-intensifying impovertization.

In "Reflections on Class Theory", Theodor Adorno discusses this, ironically, in the context of why
Marxist dialectic has had great praise from the "bourgeoise and their supporters" (Reflections, 94),
because of its dynamistic quality. Adorno quotes Ernest Troletsch's praise, and in that you even see
some of the twist inflicted back at the reader; Marxism adapts to the "fundamental mobility of the
real" (Ibid.).

"Dynamic" labor under neoliberalism is precarious labor, and in this change of term as "gig" labor,
nothing is actually changing. Rather than the job or the career changing in a meaningful way, the
precarity has been made more widespread. The prehistory's contours and the need of capitalism to
have a class of people in a position of extreme vulnerability shines through, and everyone knows it
in some way. Life simply gets faster as we get older--or, perhaps, has the increase in labor
concentration and precarity simply sped it up every generation so consistently that we have taken it
as a simple dictum of aging? Observing the small moments of suffering is one thing; noticing the
threads weaving through them is another. It's tiring. Adorno recognizes this in the way we terrorize
each other when some sort of prehistory comes to the forefront of discourse.

"The thought which does not pursue the [opposing poles of our political discourse] incurs [the
realists'] boundless wrath. It reminds them that something which exists only to be smashed still has
a voice: nature, with which the lies of the nationalist folklore-lovers are full to overflowing.
When its sound interrupts, even for a moment, their chanting chorus, the dread they seek to drown
with their voices, and which lives on in their rationalized, broken hearts as in every animal, makes
itself heard."
-- Theodor Adorno & Max Horkheimer, "Man and Beast", part of "Notes and Sketches",
   from *Dialectic of Enlightenment* (1947)

Forms of dynamism are made immanent by capitalism. The main goal of the technology industry as it
exists today, is to disrupt all avenues of economic work and claim them, infusing itself into every
sentence where work is a verb. This is, to reiterate, a core part of our economic: capitalism
divides labor, specializes, further and further but simultaneously and contradictingly *must*
consolidate it in the same breath, according to the needs and efficiencies it dictates of our
moment. This is the dynamism of capitalism, and the dynamism of history, and the dynamism of
dialectic. Natural law sees violence as a natural dictum and as law undergirding Liberalism, it is
unquestioned and unquestionable (Critique of Violence, 237). The idea that this dynamism, which only
intensifies the violence always of the past, is actually useless, is itself useless in the
discourse.

Technology is no stranger to collaborating with instruments of suffering—the more pessimistic
could say it is the main goal of technological industry today, or the more ideological entangled
could say that a tool is for doing, it makes no statement towards its intended use. Is that so? The
internet might appear to be the most hopeful example of a technology which has become use-agnostic,
but this is not true: the Internet's precursor was ARPANET, funded by the Department of Defense,
and only in 1992 was the Internet Society founded explicitly with the goal to "assure the open
development, evolution and use of the Internet for the benefit of all people throughout the world".
Existing in a harsher rendition of the old classics, a new decentralization of access to the tools
of creation and dissemination has combined with less ability to escape them or chose otherwise, as
the whole world has moved online. The freely-aimed research funded by an instrument of imperialism
was only then redirected to be for the benefit of all people, yet capitalism is still clawing it
towards consolidation; we all view the same five websites, social media. It is literally impossible
for you to be a citizen in this digitalized world without interacting with Amazon Web Services or
Google Cloud Platform, since every tech company has contracted out to their infrastructure. Any
possibility from the open conception of the internet as a stage of change needs to be drained.
Spread, then consolidate. Were we to try and exit this dialectic between the concealed and the
true, we would currently, become incomprehensible, if not silenced by being deemed "not viral". The
ideology finds incomprehensible our positions that no progress has been made: the laws changed, and
a few years ago you didn't have a smartphone in your pocket. The same notion of being viral is the
same notion of being tangible and comprehensible in an ideological framework. Facebook does not
suggest dialectics, and if it did we'd be wondering what it is trying to sell us this time.

The problem lies in a lack of action. Critical theory will say to be dialectical and consider what
of the old you uphold even in the new, but industry of course does not concern itself with this.
Technology as an industry must decide where it stands, and furthermore, it needs activism and
organization to enact that decision. Technology as an industry does not currently have the
liberatory potential of technology the noun. Historically, an impression of progress has ran so
deep in tech circles that it has meant a complete lack of recognition as to why collective
organization is necessary. The industry started with unusually individualistic workers, who,
tinkering around in their garages (so goes the romantic notion of the Hacker and his Hacker Ethic),
lived through a time of economic prosperity and neoliberalization in the 1960s to 1990s, with
neoconservatism capping off its more formative period. With the proliferation of work-from-home as
well, perhaps the organization might begin to look more apparent: since we cannot be in communion
together physically, since our employers can view our messages and control our discussions, and
since the place of work in the daily life has left the physical office, it is ever-more imperative
that we speak with one voice, apart from the ruling class. Currently, most of tech still sees
itself in Walter Benjamin's depiction of the leftist intellectuals (The Author as Producer 773): as
mental laborers, they are perhaps Artists or Authors, they do not merely work a machine as in a
factory worker, it is a creative artistry as well as a manufacturing potentiality. Tools, created
by tools, creation directed by artistic and philosophical methods and designs. A separate class,
they are different from those needing organization, when as, to the contrary shown in every
industry with a boom like this, the coming ubiquity of their work will soon make it apparent their
labor is just as precarious and struck by the old impoverishment as all the others that came before
them. "The age when people could build barricades now lies almost as firmly in the past as the time
when a craftsman's trade was a solid foundation of life." (Reflections on Class Theory 96)

Technology responds to our social issues, our economic issues. Apple collaborates with mental
health researches at UCLA, and our pocket surveillance apparatuses will soon find it their job to
solve what it takes to account for government inaction. Phones scan for COVID exposure because the
useless half-hearted public health measures have made it necessary to appear to be able to do
contract tracing. Online therapy has developed because of a lack of mental health infrastructure
distribution. Your phone will try to figure out if you're depressed, maybe your online-only
insurance provider will increase your premium, since you got a premium discount you couldn't refuse
for connecting your Apple Health to your insurance's phone app. Is it so much a stretch to say the
lines of domination and surveillance will keep weaving so intricately that what was once a dynamic
tool of decentralization and removal of class barriers will instead just become another tool used
to oppress? "The omnipotence of repression and its invisibility are the same thing." (Ibid.). You
are coerced, insofar that to live is a constant coercion, and that not to live is your other
option. If the dynamism of technology has produced a mere appearance of change in relations, what
would a tech do were it laser-focused on organizing and liberating, raising the consciousness of
its users, and most concerned with the slow clarification of the world than the fast response? _A
tool is best when it resists the "neutral" orientation._

When I was young, I grew up at _just_ the right moment in history to get the last gasp of computers
before they would start to become intangible.
