= some aphorisms
:description: 
:docdate: 2022-01-08
:keywords: philosophy, events, aphorisms

It does not follow that from a "winter of death", comes forth a summer of life.

'''

_in something between_ When faced with binary ways of thought it can often appear that a trinary one
leads out of the limitations of binary thought. Unfortuantely, this instead leads to a demarcation
of type zero and type two, with type one standing to describe the expansiveness of all of existence,
if anything.

'''

_nothing genuine_ At times, creating art with an awareness of class relations and the wrongness of
life has a tendency to feel more akin to palative care, hospice care, than an expression of all
life, its wrongness, the reality of its struggle.

'''

_parasocialization_ One of more terrifying aspects of social media is the way that a state of
depression or other expression of intense sadness is now both _expected_ and additionally no cause
for alarm. It is a common sort of Content present on these sites, gathering pity likes, yet it
remains unspeakable, not a topic of conversation. Everyone has a space they vent in, where all their
bad thoughts are represented, a museum of one's complete negative legacy; and what was once
relegated to the realm of the personal diary, the life in letters, and intimate conversation with
friends/family/lovers, is now a whole mode of public private life. While the expectation of constant
accessibility through instant messaging and quick distribution of Posts remains intact, the
possibility of an equally quick comforting and repairing of a one's sorrow remains difficult and
unlikely. Not due to insensitivity, but perhaps because knowing sadness in the moment it occurs is
more painful than discussing it; a medium such as an algorithmic media not only creates the
appearance of truly knowing someone's interior life, it also makes it impossible to interface with
it. Worse, it can create both a sense of "I must do something now, this person is in such intense
distress, yet no one is acting, no one is doing what is right", and another one: "I too am so
wrought with distress and damage and neurosis myself, I almost wish the extent of my own pain were
so great and distinct and profound as to ensure that I could harness it and extract from it the
solution to all those who too suffer in even the smallest sort of resemblance."

'''

