= jan kon tonsi
:description: tenpo la ale tenpo sina li e ni: wan ale li monsuta e ante ale
:docdate: 2021-11-22
:keywords: trans, philosophy, critical theory

[.lead]
--
tenpo pini lili la lon tomo sona mi lukin li kama sona e lipu lili tan lipu _Dialectic of
Enlightenment_ (lipu ni li tan jan Max Horkheimer en jan Theodor Adorno). lukin mi li pali e ni:
mi kama awen sona e tenpo lili pi tomo sona pini. tomo sona ni li pana e sona pi tenpo pini tonsi.
lipu kama ni li tan lipu tawa tomo sona ni; mi pilin pona tawa lipu ni la, mi wile pana e lipu ni
tawa sina.
--

[nanpa wan la mi wile toki e ni: mi kepeken e nimi "tonsi"; insa pi lipu ni la, mi kepeken nimi
"tonsi" e tawa ni: nasin pi nimi "tonsi" li taso ala toki e nimi "non-binary" (tan toki Inli). kin,
nimi ni li ken toki e nasin pi tawa "kon" (taso la, toki pi nasin "gender" la, nimi kon li pona ala
tawa mi...). mi pilin nasa e ni: nimi ni li toki e nimi "non-binary" sama e nimi "transgender" sama
e nimi "gender" (tan toki Inli).]

'''

mi tawa pali e linja pi ike lukin. lukin ni li toki e utala, taso la, utala ni li wile tan toki mi.
tenpo ale la, linja pi tawa tonsi jan en moli li kama utala. pana toki pi utala ni li wile mi.

tenpo pini la, mi lukin e lipu. lipu ni li pana e sona lili tawa mi; tenpo ni la mi ken ala alasa e
tan pi lipu ni. mi kama kepeken lipu lon; sona mi li tan ala e tan lipu ni. kin, mi kama kepeken
pilin mi tan tenpo pini mi.

== ale pini li monsuta e ale lon

insa lipu kipisi "On The Theory of Ghosts" la, lipu li jo e toki pi nasin wan pi jan Sigmund Freud.
toki pi nasin ni li toki e ni: nasin pi tan jan kon. o lukin e toki ni:
[quote, "kipisi On The Theory of Ghosts, tan lipu Dialectic of Enlightenment"]
____
At the stages of humanity's development when death still appeared as a direct continuation of life,
the abandonment of the living in death seemed necessarily like a betrayal, and even in enlightened
times the old belief is not quite extinguished. [...]

lon tenpo pi jan pali la, tenpo ni: moli li sama lukin e ale tenpo la, weka pi jan lon li  

[...] It might almost be said that the concept of human life itself, as the unity of a person's
history, has become invalid: the individual's life [...] has lost all continuity between conscious
remembrance and involuntary memory [...] Individuals are reduced to a mere succession of
instantaneous presents, which leave behind no trace, or rather, the trace of [...] something
irrational, superfluous, utterly obsolete.
____

The past is viewed with contempt and is liable to be suspect. As seen plenty with current online
toxic transphobic discussions, with transphobes insisting they can always tell if someone's trans by
their appearance, their jawline, voice, what have you, this isn't really something hard to draw
connection between. There's plenty of things to point to as examples of this, and I'm not really
going to belabor an explanation of how people view trans people's lives prior to transitioning with
contempt and a discomfort, if not for sake of post length then for my own emotional sanctity.

This shows through in how, until maybe just the past six years or so, often a point of advice among
cis people when it came to interacting with transgender people, there would often be advice to not
ask about someone's backstory, or to see baby pictures, or anything like that. Obviously, this is
not something cis people think to ask often of other cis people, because they are questions which
are grounded in an expectation that a trans person's history is something which conflicts with their
current appearance and current interpretation by the asker. The questions are marked with the
expectation of a contradiction and following, a revealing of someone's visible history; the
expansion of the succession of presents with no trace into a contrast which demonstrates quite
clearly, a progression.

I had to show my mom a few timelines of the appearances of trans women who took hormones to convince
her I'd look "normal" at the "end" of all of her pain. The perceived gender of the past or the
current (pre/non)-medical transition is viewed with truth, as is the past perceptions; the true
gender of the present is liable to be suspect.

== forget yourself, girl

The text continues...

[quote]
The threateningly well-meaning advice given to emigrants that they should forget the past because
it cannot be transplanted, that they should write off their prehistory and start an entirely new
life, merely inflicts verbally on the spectral intruders the violence they have long learned to do
to themselves. They repress history in themselves and others, out of fear that it might remind
them of the disintegration of their own lives, a disintegration which itself consists largely in
the repression of history.

:url-trans: https://www.umass.edu/stonewall/sites/default/files/Infoforandabout/transpeople/genny_beemyn_transgender_history_in_the_united_states.pdf

Here I'll be citing a book chapter, {url-trans}[Transgender History in the United States],
by Genny Beemyn.

The fact that Adorno was writing this section during his time in California after escaping Nazi
Germany is obviously not something I desire to co-opt or appropriate by comparison, but this
"threateningly well-meaning advice" is not unique to people who have emigrated, which I don't think
is controversial to point out.

I say this because not too long ago (the 1960s-1980s), transsexual people were explicitly encouraged
by physicians and medical professionals to hide and lie about their past. They were told to invent a
childhood matching their post-transition gender, sever ties with old friends and make new friends
with people who didn't know them prior to transition, change jobs, even move to another city to
avoid the possibility of being outed.

[quote, "\"The Post-Christine Era\", page 18, Transgender History in the United States, Genny Beemyn"]
Given the extreme social stigma against transsexual people, many did not need much encouragement to
'disappear' if they could.

And I say not too long ago, but this is not a long ago thing. I will go back to the baby pictures
and the questions about childhood: the way transphobia from the cis inquirer is avoided in lieu of
their actual understanding and acceptance of a transgender person's history, is through the trans
person's forgetting and a repression of their prehistory.

:url-react1: https://www.nytimes.com/2019/10/18/opinion/sunday/gender-transition-death-grief.html
:url-react2: https://www.theatlantic.com/family/archive/2020/07/i-love-my-trans-daughter-but-im-still-struggling/613786/
:url-react3: https://www.justplainbeth.com/you-can-grieve-and-support-your-child/
:url-react4: https://www.sciendo.com/article/10.2478/genst-2020-0011

The comparison between the dead and the transgender person here is not simply that, because we also
see it in terms like "deadname" (a transgender person's former name, if they changed it), or in the
way {url-react1}[it's not at all uncommon]
{url-react2}[for parents to react]
{url-react3}[to their child's real gender identity]
{url-react4}[with a sense their actual child is dying]. Of course, even a term like deadname isn't
meant literally--one can easily reject the idea that because they've come out, the old them is dead,
yet can still use the word "deadname" without having a problem with it.

I still get this sentiment on rare occasion in part because my own coming out coincided with moving
off to college, and because I changed my name after moving up here; if your mom thinks you became
much more argumentative when you moved away, imagine how curious it must be to be accused of being
more argumentative because you're no longer pretending to identify to her or anyone else as a man.

Even recounting that, I can see that I myself even did this: move to another city to avoid the
possibility of being outed, developing new friendships, and so on, though no one told me to do that.
A clean slate. The person who the past gender used to inhabit is viewed as a ghost, because society
wishes not to interact with or give an accepted continuity to their life through a time of
transition--they repress history in themselves in fear that disintegration will cause a new
disintegration.
