= biological indicators
:description: written in a haze after reading a paper
:docdate: 2021-11-09
:keywords: philosophy

:url-housewife: https://thenewinquiry.com/fucking-like-a-housewife/

Marriage is an experience I have never been given lens to willfully aspire to--my mom insists
someone was my girlfriend in elementary school--this has colored my impression of heterosexuality.
It is often something read onto people, rarely does it feel as something entirely genuine. But we
must, from the complete inundation of it that constitutes all of media until what feels to be just
a recent flash in society's history, assume it's something real to some people out there. In reading
older feminist texts, which speak to a universal experience and oppression that constitutes Woman it
feels like it merely pokes at the uneasiness I'm having difficulty articulating.

[quote]
--
This is also a fantasy of a man who comes back home.
[...]
THIS is an erotics of abandonment in the other: a kind of ecstasy in the Catholic sense. St. Teresa
of Ávila’s slack mouth.

As I say, these are fantasies, but of what? An endless deferral of Self. Of incomplication.
--

I am being ascribed to, an experience and oppression which I was not given until an age that I was
expected to know the script. Yet this script is one which at the same time is an oppression and
force of normalization that I have to be willing in some way to take on as a part of my standing in
and of womanhood and recognition as being part of that group of Woman. Woman is heterosexual where
woman is a body without sexuality--they both have genitalia.

It is often the case that I am aware of how my perception of myself, contiguous throughout my years
as it is, includes a parsing and a processing of a maleness that I was supposed to take up, yet
rejected. An organ rejected. To people otherwise who have only met me at some point in the past
years, that remains an invisible past too touchy and difficult to be worth learning about, and
indeed something too touchy and difficult for me to be analyzing and walking through; my important
differentiating experience here often only remains something to utilize the transient and
constantly-reiterative power of memory upon. It is revised, postscript elaborated upon, rationalized
through whatever art and theory I gained since then.

[quote]
At times I think everything about my desire is tired, tied up in outmoded whorishness.

The mythological Woman which exists as a constant, the "most" oppressed in the misguided, white,
second-wave feminist notion, she is who I am supposed to see myself through: the indoor-kept
housewife, her apron, her heterosexual desire, the expectation on her that she place her home in the
body and the mind of the breadwinner, the cultural figuration that is the housewife rings empty yet
as something that I am expected to look to yet never attain, for what notion womanhood there is left
for me to have. It continues to be deconstructed, perhaps more usefully, by people who have moved o
from the identity of woman--but the thing I identify with remains, if just a projection of society,
a shadow puppet on the cave wall.

[quote, "Jamie Hood - {url-housewife}[Fucking Like a Housewife]"]
We talk about what he will be like as a father. We talk about how I'd make a great mom, although we
do not explicitly talk about the fact that I cannot have children. How unlikely it is even that I'll
be allowed to adopt or go through a surrogate, no matter how intense my want is.

The argumentative utility of the uterus and the vagina is to do the no-longer-submissive
metaphorical penetration of the impenetrable, physical, eternally-dominant phallus. In the breaking
down and troubling of heterosexual and patriarchal discourse however, it will fall flat to the ears
of a reader who reads from the standpoint of the metaphorical unseparated from the biological, the
metaphysical from the physical. What surgery gives someone a metaphysical uterus, or takes away the
psychoanalytical notion of the phallus?

To be identified as or to be belonging to Woman is to identify with the potentiality of what the
uterus represents, a lifegiver and stage in contrast to a lifemaker and actor, already from this a
binary passive versus active. But it is not that simple, given that as a woman, not a Woman, not
having a boyfriend or husband or more specifically _a uterus_ involved, I am never identified by
others as a potential lifegiver, only an actor who acts, who does thing. My biological state
influences where I stand in the metaphysical discussion, trans women are never the lifegivers but
the ones who come to inhabit, in some sense. Another aspect of this belonging is to have, in some
sense, the dialectically bound receptiveness, the lack of prescription, of the vagina--but only on
the metaphorical level. To identify any further is not welcome by any party.

[quote]
To the final point, what I am also asking here is: Are trans women de facto alienated from these
structures, or is there a path toward reimagining the Housewife beyond the bounds of cisness,
whiteness, and subjection under late-capitalist variations on the family? In some sense, this is
also a question of whether or not a certain fashioning of heterosexual desire--or heterosexuality as
a determinable identity and ongoingness in and of itself--can only and ever be a dead remnant of a
racist and misogynist structuration of desire within a system built on commodity fetishism.
