= diary: who funds the police in my head?
:docdate: 2021-03-16

it's just a limited time i guess. there's only so much time i have to talk to you, you're busy
most of the time. i don't talk much about the others to you because it's just, i guess i assume
people would generally find it alienating to hear about my partners that aren't them, if they're
not in a committed relationship with me. i don't talk about my relationships to people irl much,
just to save myself the trouble. i know who to refer to as my girlfriend/roommate/friend
depending on the situation. i wish I didn't feel the need to present myself conventional, i just
can't do it all the time, i'm too weird to be honest with everyone in my life, maybe

> Why can't I be more conventional?
> People talk, people stare, so I try
> But that's not for me, 'cause I can't see
> My kind of crazy world go passing me by
> -- exerpt from "why try to change me now", composed by cy coleman and joseph a. mccarthy, 1952)

i don't know how to describe my relationships, or my sexuality, or my gender, they just are. so i
find myself using journals for classes as therapy sometimes. i don't find discomfort in my
gender, but I do wish i could be closer to my ideal expression. not taking risks probably sets me
back. i know some people find shame in having crossdressed as a young trans person but i guess i
just find some regret i didn't ever try. maybe i was scared? it's possible, but i've just lost a
lot of memory for those times in my life. i don't remember a lot of things clearly from those
years. i just know i didn't ever try.

one time when i was 17 i think, i was going to go over to a friend's house and they were gonna do
my makeup. i found an excuse the day of to get out of it. i was just too scared. i've spent so
much of my life scared of what people think of me. i just don't want people to see me as a freak
or a weirdo. i know I'm weird but i wish i weren't. i've spent so much effort trying to not do
things people would see me weird for that I've probably held myself back from trying things that
would actually make me more conventional of a woman. i am scared at the thought of trying new
clothes, of changing my voice, of having pride in my style and my looks, of experimenting with
makeup, that i just don't even try. what am i waiting for? like who's permission do i need to do
these things now? who funds the police in my head?
