= Kylie McClain
:nofooter:
:linkcss:
:stylesheet: ./style.css

:compress:
:pdf-theme: ./resume.yml

ifdef::backend-pdf[]
[.center,cols="3*^",width="75%",frame="none",grid="none"]
|===
|mailto:kylie@somas.is[]|https://somas.is/|https://www.openstreetmap.org/relation/178973[Boone, NC]
|===
endif::[]

ifndef::backend-pdf[]
link:resume.pdf[Available in PDF format as well.]
endif::[]

[.text-center]
Hi! I'm Kylie, a 23 year old philosophy student hailing from North Carolina. +
Please email me at mailto:kylie@somas.is[] to request further details. I can provide references.

:url-debian: https://debian.org
:url-arch: https://archlinux.org
:url-alpine: https://alpinelinux.org
:url-exherbo: https://exherbo.org
:url-musllibc: https://musl.libc.org
:url-skarnet: https://www.skarnet.org
:url-execline: {url-skarnet}/software/execline
:url-s6: {url-skarnet}/software/s6

== Work

:url-tss: https://support.appstate.edu/services/technology-support-center

* *Student IT Technician* at {url-tss}[Appalachian State University Technology Support Services]
  _(2018-present)_
    ** Virus removal, data backup, hardware diagnostics, ticket management via Jira.
    ** Customer service, explaining repair steps taken to customers upon them picking up their
       computers.
    ** Known as the only person in the office who knows what they're doing with Linux, usually
       machines running Linux that are having problems get referred to me. `:-)`

== Education

* https://appstate.edu[Appalachian State University] _(2018-present)_
    ** Pursuing a *Bachelor of Philosophy*, majoring in Philosophy and minoring in Gender, Women's
       and Sexuality Studies.
* Rowan-Cabarrus Community College _(2016-2018, transferred)_
* Concord High School _(2012-2016, graduated)_

== Skills & Interests

*Software*::
    {url-alpine}[*Alpine Linux*], {url-exherbo}[_Exherbo Linux_], {url-arch}[*Arch Linux*],
    {url-debian}[Debian GNU/Linux], Windows 10, *POSIX Shell/bash*, {url-musllibc}[*_musl libc_*],
    {url-s6}[*_s6_*], {url-execline}[*_execline_*], name a Unix tool, I've probably used it.

*Infrastructure experience*::
    *Jira*, *GitHub*, GitLab, Gerrit, *Gitolite*

*Interests*::
    Minimalist system design, system administration, small systems, efficient use of resources.

[small]#Italicized: projects I have contributed to in some way. Embolded: things I'm currently using.#

== Open-source activity

* *Core developer*, {url-exherbo}[Exherbo Linux] _(2014-2017)_
    ** Coordinated efforts with approximately 20 other developers via IRC.
    ** Added support for new platforms such as {url-musllibc}[musl libc], and ARMv7.
    ** Wrote bootstrapping documentation for new processor architectures.
    ** Wrote documentation for complex code previously written by others.

== Side projects

* https://mutiny.red[Mutiny], a Linux distribution/research project aiming for unique, coherent,
  and fun computing. _(2016-present)_
* https://wiki.musl-libc.org[musl libc wiki], a community-maintained wiki documenting the musl
  libc project. I maintain the build system for it, the stylesheets, and host it.

== Hobbies

* https://somasis.bandcamp.com[Music making], using FL Studio.
  _(2012-present, probably until I die)_
* Somewhat active contributor to https://openstreetmap.org/user/somasis[OpenStreetMap]. +
  It's helped me to find the world around me and the community I live in a lot more interesting. +
  Anywhere new I go ends up on the map sooner or later.

