= Introducing...
:page-description: A short introduction of my new website, the process making it, and some life \
                   events.
:page-tags: meta

Welcome! This is my new website. I became discontent with the way my old one was, since it mostly
served as a landing page for all my other stuff. With this new site, I'm hoping to actually get into
writing some things and finding a place to flesh out thoughts rather than just letting them sit
around in my head.

Creating this site has been a fun task. I've done enough things with static sites to kinda hate them
at this point due to my stubbornness; I'll give a short overview of the process it's been.

After making https://github.com/somasis/makedown[makedown], and the annoying chore that proved to be,
I started to make myself more familiar with https://asciidoctor.org[AsciiDoctor]. I eventually
started to work on making content with it, and found it to be a joy to write in. Having an actual
standard developed around it and being extended with actual features as needed is something that
Markdown still hasn't really caught up to as the years have gone on, despite the work of the
CommonMark group.

Before writing setting up this site, I had been first working with a long-time document that I had
laying around: my pile of notes on https://mutiny.zone[Mutiny], my kinda-sorta project to make a
Linux distro that can be best described as "what would my computer look like if we already had
communism".

I've made almost no progress on it, but that's just how the cookie crumbles I suppose. It's been a
fun experience in writing documentation and _thinking_ about system architecture at least. It is a
testament to how I focus on optics too much that I spent too much time perfecting the font choice
for the Mutiny(TM) "I totally didn't steal this aesthetic from Halt and Catch Fire, the show that I
now see as a personal lesbian awakening"footnote:[Have you _seen_ Mackenzie Davis/Cameron Howe in
that show? Jesus.] logo than I did actually making the stupid thing.

.Keep it real though, you know it's really cool lookin'.
image::https://mutiny.zone/logo.svg[Mutiny logo]

After discovering that AsciiDoctor was really fun to work with and generated some very
pretty documentation by default, I've basically given up on Markdown. Another perk, one that drew me
into it when working on Mutiny documentation, was that it allows for rendering into HTML and man(7)
format. One of choices with Mutiny was that all documentation should be accessible from the system
without needing to access the internet, so this was pretty good.

Eventually, I altogether gave up on trying to make my own static site build systems, and gave in to
the fact that I'm exhausted and my time on this Earth is limited. That's why it says "created with
Jekyll" on the footer. https://jekyllrb.com/[Jekyll] has been a joy to use and it's been nice for
just getting the site running and not spending what feels like eternity working on making the tools
to make the site.

Aside from this, I hope to discuss on here some of my more recent habits: OpenStreetMap 
footnote:[You'll be seeing too much about this one
https://www.openstreetmap.org/user/somasis/history[probably].], philosophy and gender studies, and
music. Hopefully I keep this up.

