= Transness and Philosophy aren't exclusive
:page-description: Some thoughts about how philosophy and trans identities interact.
:page-tags: [trans, philosophy]
:page-redirect_from: /2019/11/14/transness-and-philosophy-exclusive.html

In class this afternoon, I began to realize these thoughts and wrote them down frantically into my
notebook, because something was bothering me that I couldn't quite grasp fully. We were discussing
Stoicism, but in particular, https://www.gutenberg.org/ebooks/2680[Marcus Aurelius' Meditations].
Discussing the use of nature in it, my professor started to speak of Aurelius' ideas of nature. Our
class was taking issue with nature and naturalism's current through Stoicism, which really ended up
being more a current through Greek and Roman philosophy anyway.

She was saying he may consider nature's good as more of a "goal-oriented" good; that is, the tree
has a goal: to grow, flourish, reproduce, and so on. However, she then went on to say that that is
good. Our previous class was very critical of the way that nature was utilized and taken as a good,
and that the universe is good intrinsically.

Nature as a goal-oriented thing tending towards good is a troubling prospect to me however, because
in my experience of what people assert as nature, people (transphobes, well meaning cis people, and
an unfortunately numerable amount of trans people) see the assigned sex at birth as being nature;
gender {identity,presentation,expression,conception} is put upon it by the self. That's where the
refrain that trans existence is unnatural comes from.

There's multiple ways to view this: gender as part of nature, identity as nature, identity as
social, gender as social, gender as choice, ..., and many many other ways. My list is lacking
nuance and depth, but for the sake of simplicity I'll say that it's not something I think much of
currently and that I'm not firmly in any camp either. For me, gender is just something I have and
I think the nature/nurture dichotomy is bullshit. Nature and nurture are intrinsically linked and
I think dividing them is a mistake, much like Descartes divided the mind and body, leaving us to
pick up the pieces with phenomenology. I digress.

How do I reconcile putting my experiences onto ancient philosophy? They were so unprepared for trans
lives, but even I know that's a lie. Trans people existed then, we always have, and philosophers
claiming to speak for the entire breadth of human experience never cared about what we have to bring
to the dialogue. Thus, I feel unwelcome to apply my experiences openly in class and to these
texts; though I know my identity is not a recent invention, I feel ignored and underappreciated for
what my experience with gender and sexuality have to add.

Part of my hesitancy could be the makeup of the class. An LGBTQ+ studies class of course, opens up
more opportunities for an atmospherically comforting way of speaking trans experiences (well, one
would hope at least). But that's bullshit too isn't it? I know a few trans people in ancient
philosophy, I'm the only trans feminine person in my LGBTQ+ studies class. Why does one present more
opportunity than the other, when I see all these opportunities slowly driving past me as I listen to
the class talk without speaking up once?

This is part of a greater narrative I have, but no one ever seems to agree when I say that gender
studies and philosophy are actually the same study.

I think it is incomplete, when one discusses identity, change, nature, and human experience when one
does not include the breadth of trans experience. These perspectives are valuable to an enormous
extent when studying this philosophy, and ancient, modern, recent, continental, all philosophy can
not and will never claim to speak to human experience if it leaves trans perspectives of philosophy
out in the cold. And, it is a mistake to not utilize that in critical, truly analyzing discussions
and lessons.
